version: '3'
services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: bookstore-microservice
    container_name: bookstore-container
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    command: ./main
